### ISSUE TITLE
Memcached extension does not successfully install from admin UI

### ISSUE THREAD

**Issue by Yamaha32088** [lucee/Lucee#32]
I get this error whenever trying to install Memcached from the admin UI. Have been searching for the answer but can't find any answers on it, seems like possible missing dependencies according to the articles I found though.
![error](https://cloud.githubusercontent.com/assets/6120946/17306694/f57a1008-57f6-11e6-8a89-7a77b9543b2f.PNG)

**Comment by bdw429s** [comment]
I just noticed this myself last week and mentioned it to @michaeloffner   
He asked me for the full stack trace.  can you provide the same thing here?

**Comment by Yamaha32088** [comment]
![2016-08-02 1](https://cloud.githubusercontent.com/assets/6120946/17345222/a37e8a02-58ca-11e6-8fce-2f236be4d816.png)

**Comment by TwentyOneSolutions** [comment]
This is not the place to report bugs/issues. Please use the JIRA at https://luceeserver.atlassian.net/projects/LDEV/issues/

Thank you.
