### ISSUE TITLE
CSRFGenerateToken() breaks when using this.sessionCluster=true in application.cfc

### ISSUE THREAD

**Issue by Yamaha32088** [lucee/Lucee#33]
We have gotten to the final stages of setting up a clustered environment with three nodes using Memcached. Everything seems to be working fine except for our login areas. We noticed that when we use the `this.sessionCluster = true` in our Application.cfc, that `CSRFGenerateToken()` creates a brand new token on every request which causes the `validate()` function to fail.

**Comment by TwentyOneSolutions** [comment]
This is not the place to report bugs/issues.  Please use the JIRA at https://luceeserver.atlassian.net/projects/LDEV/issues/

Thank you.
